# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('top_subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('bottom_subtitle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['top_subtitle'],
                'db_table': 'offer_details',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_descrtiption', models.CharField(blank=True, max_length=100, null=True)),
                ('product_regular_price', models.IntegerField(blank=True, null=True)),
                ('product_selling_price', models.IntegerField(blank=True, null=True)),
                ('product_stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['product_name'],
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['category_name'],
                'db_table': 'product_category',
            },
        ),
    ]
